### PR TITLE
Modify syntax errors，Translate the updated content of the readme file

### PR DESCRIPTION
**Pull request by didu233**

### CODE REVIEW

**Review by luckyyang — DISMISSED** [review]

**Comment by liberhe** [comment]
去掉这个。上面链接已经有了。
**The Austrian school of economics**

 [The curriculum of Austrian economic school on blockchain(1)](https://mp.weixin.qq.com/s/OZhhmVliPzT7xIiTxPhGKQ)
 [The curriculum of Austrian economic school on blockchain(2)](https://mp.weixin.qq.com/s/TI0e7sNuC76ohEQgADwcLQ)
 [The curriculum of Austrian economic school on blockchain(3)](https://mp.weixin.qq.com/s/7CaYMAoB636YA1rBPBJ-wQ)
 [The curriculum of Austrian economic school on blockchain(4)](https://mp.weixin.qq.com/s/-5yszc6NKeepuYQ-r6XdIw)

**Comment by didu233** [comment]
> 去掉这个。上面链接已经有了。
> **奥地利经济学派**
> 
> [奥地利经济学院区块链](https://mp.weixin.qq.com/s/OZhhmVliPzT7xIiTxPhGKQ)
> [课程](https://mp.weixin.qq.com/s/TI0e7sNuC76ohEQgADwcLQ)[(1)](https://mp.weixin.qq.com/s/OZhhmVliPzT7xIiTxPhGKQ)[奥地利经济学院区块链](https://mp.weixin.qq.com/s/TI0e7sNuC76ohEQgADwcLQ)
> [课程](https://mp.weixin.qq.com/s/7CaYMAoB636YA1rBPBJ-wQ)[(2)](https://mp.weixin.qq.com/s/TI0e7sNuC76ohEQgADwcLQ)[奥地利经济学院区块链](https://mp.weixin.qq.com/s/7CaYMAoB636YA1rBPBJ-wQ)[课程](https://mp.weixin.qq.com/s/-5yszc6NKeepuYQ-r6XdIw)[(3)](https://mp.weixin.qq.com/s/7CaYMAoB636YA1rBPBJ-wQ)
> [奥地利经济学院区块链课程(4)](https://mp.weixin.qq.com/s/-5yszc6NKeepuYQ-r6XdIw)

我是按着readme里多加进去的呀  要删了吗

**Comment by liberhe** [comment]
> > 去掉这个。上面链接已经有了。
> > **奥地利经济学派**
> > [奥地利经济学院区块链](https://mp.weixin.qq.com/s/OZhhmVliPzT7xIiTxPhGKQ)
> > [课程](https://mp.weixin.qq.com/s/TI0e7sNuC76ohEQgADwcLQ)[(1)](https://mp.weixin.qq.com/s/OZhhmVliPzT7xIiTxPhGKQ)[奥地利经济学院区块链](https://mp.weixin.qq.com/s/TI0e7sNuC76ohEQgADwcLQ)
> > [课程](https://mp.weixin.qq.com/s/7CaYMAoB636YA1rBPBJ-wQ)[(2)](https://mp.weixin.qq.com/s/TI0e7sNuC76ohEQgADwcLQ)[奥地利经济学院区块链](https://mp.weixin.qq.com/s/7CaYMAoB636YA1rBPBJ-wQ)[课程](https://mp.weixin.qq.com/s/-5yszc6NKeepuYQ-r6XdIw)[(3)](https://mp.weixin.qq.com/s/7CaYMAoB636YA1rBPBJ-wQ)
> > [奥地利经济学院区块链课程(4)](https://mp.weixin.qq.com/s/-5yszc6NKeepuYQ-r6XdIw)
> 
> 我是按着readme里多加进去的呀 要删了吗

去掉了，误加的。后面中文文档会删除

**Comment by didu233** [comment]
> > > 去掉这个。上面链接已经有了。
> > > **奥地利-经济学派**
> > > [奥地利-经济学院区块链](https://mp.weixin.qq.com/s/OZhhmVliPzT7xIiTxPhGKQ)
> > > [课程](https://mp.weixin.qq.com/s/TI0e7sNuC76ohEQgADwcLQ)[（1）](https://mp.weixin.qq.com/s/OZhhmVliPzT7xIiTxPhGKQ)[奥地利-经济学院区块链](https://mp.weixin.qq.com/s/TI0e7sNuC76ohEQgADwcLQ)
> > > [课程](https://mp.weixin.qq.com/s/7CaYMAoB636YA1rBPBJ-wQ)[（2）](https://mp.weixin.qq.com/s/TI0e7sNuC76ohEQgADwcLQ)[奥地利-经济学院区块链](https://mp.weixin.qq.com/s/7CaYMAoB636YA1rBPBJ-wQ)[课程](https://mp.weixin.qq.com/s/-5yszc6NKeepuYQ-r6XdIw)[（3）](https://mp.weixin.qq.com/s/7CaYMAoB636YA1rBPBJ-wQ)
> > > [奥地利经济学院区块链课程（ 4)](https://mp.weixin.qq.com/s/-5yszc6NKeepuYQ-r6XdIw)
> > 
> > 
> > 我是按着readme里加进去的呀要多去
> 
> 删除了，误加的。离开中文文档会删除

好的

**Review by yanyanho — APPROVED** [review]

**Review by yingjingyang — APPROVED** [review]

**Review by luckyyang — APPROVED** [review]

**Pull request merged**
