### PR TITLE
add high-quality blockchain course resource

### PR DESCRIPTION
**Pull request by D-lyw**
北大肖臻老师的[《区块链技术与应用》公开课](https://www.bilibili.com/video/BV1Vt411X7JF)，是我迄今为止发现的国内极少数优质的区块链和加密货币相关课程。希望能给加上，对想学习区块链的同学有所帮助。

### CODE REVIEW

**Review by maroonstar — APPROVED** [review]

**Comment by maroonstar** [comment]
Looks good to me.

**Comment by xrdavies** [comment]
Thank you for your contribution.
This course is for beginners, and this repo is for those guys who already know what is blockchain and wanna get more practical exercises.

**Comment by D-lyw** [comment]
> Thank you for your contribution.
> This course is for beginners, and this repo is for those guys who already know what is blockchain and wanna get more practical exercises.

Sorry, I don't think this course is for beginners who have no idea about blockchain. In my option, this course is at the same level as other courses, like MIT Online Course.

**Comment by liberhe** [comment]
> > Thank you for your contribution.
> > This course is for beginners, and this repo is for those guys who already know what is blockchain and wanna get more practical exercises.
> 
> Sorry, I don't think this course is for beginners who have no idea about blockchain. In my option, this course is at the same level as other courses, like MIT Online Course.

add WeChatID yanyanho126 to join the group

**Review by liushooter — APPROVED** [review]

**Pull request merged**
