### PR TITLE
Add crypto course resources

### PR DESCRIPTION
**Pull request by huwangtao123**
Add crypto course resources
* DEFI MOOC by UC Berkeley and other Top University
* CryptoZombie by Loom Network

### CODE REVIEW

**Review by luckyyang — APPROVED** [review]

**Review by maroonstar — CHANGES_REQUESTED** [review]
Thanks for your pr, but we already have there two links in our docs. You can find them in :
- README.md line 67
- docs/basic-knowledge-en.md line 8

**Comment by huwangtao123** [comment]
You are right. I don't notice that.  
Personal suggestion:
1.  Keep all the md file under docs as member recommend read, with link or personal comment. (It will encourage new user to do their first PR and contribute their own opinion)
2. Keep the root README.md as official suggestion.

**Comment by maroonstar** [comment]
Good suggestion :)

**Comment by liberhe** [comment]
> You are right. I don't notice that. Personal suggestion:
> 
> 1. Keep all the md file under docs as member recommend read, with link or personal comment. (It will encourage new user to do their first PR and contribute their own opinion)
> 2. Keep the root README.md as official suggestion.

I' am sorry that  have not send you the root readme. Thanks your contribution.

**Comment by huwangtao123** [comment]
> Good suggestion :) You may join our discord first: https://discord.gg/cRYNYXqPeR

yes, i just joined the discord. The original discord link in github is expired. 
What's the next step? Should i merge this commit or we might change doc folder to more feedback style (maybe good mirror link, twitter thread, some personal idea) for more contribution.

**Comment by maroonstar** [comment]
I've just updated discord link, and other Official links, thanks for remind us.

**Review by maroonstar — APPROVED** [review]

**Pull request merged**
