### PR TITLE
In the Chinese readme file, modify a punctuation mark

### PR DESCRIPTION
**Pull request by ZhaoQian888**

### CODE REVIEW

**Comment by liberhe** [comment]
> No description provided.

Please add more information .

**Comment by ZhaoQian888** [comment]
just add a punctuation mark。at `同时欢迎大家添加推荐书籍，请在此文档 [书籍推荐](./docs/books.md) 中录入。`
I think this sentence should end with a full stop

**Review by luckyyang — DISMISSED** [review]

**Comment by luckyyang** [comment]
Approved this PR, although this can not be the ticket to enter our developer group

**Comment by maroonstar** [comment]
Thanks for PR, you may join our discord

**Review by liberhe — APPROVED** [review]

**Pull request closed without merging**
