### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xxxeyJ**
#Safety tools add Shining

Shining is a tool that enables engineers to remotely pull smart contract code in multi-file situations.

### CODE REVIEW

**Review by jhfnetboy — APPROVED** [review]
great~

**Review by maroonstar — CHANGES_REQUESTED** [review]
This doesn't look like a security tool.

**Comment by xxxeyJ** [comment]
But this is the tool I used in the audit phase.

**Comment by maroonstar** [comment]
You may put it in this repo https://github.com/rebase-network/Dapp-Learning-Arsenal/blob/main/2-Solidity.md

**Pull request closed without merging**
