### PR TITLE
增加Uniswap-V2白皮书中文版

### PR DESCRIPTION
**Pull request by xiangzhengfeng**

### CODE REVIEW

**Review by maroonstar — APPROVED** [review]

**Review by xrdavies — CHANGES_REQUESTED** [review]
Sorry, could you explain why not using links instead of files? Is it a private version?

**Review by liberhe — APPROVED** [review]

**Comment by xiangzhengfeng** [comment]
> 抱歉，你能解释一下为什么不使用链接而不是文件吗？是私人版吗？

Because the link only points to a resource address, the resource is easily changed. Especially if the reference link to the public repository changes and the corresponding maintenance personnel have left, the file may be permanently lost and can no longer be found. If the community still wants to use links instead of files, I can also use links to introduce static resources.

**Comment by xiangzhengfeng** [comment]
> Sorry, could you explain why not using links instead of files? Is it a private version?

Reply: Because the link only points to a resource address, the resource is easily changed. Especially if the reference link to the public repository changes and the corresponding maintenance personnel have left, the file may be permanently lost and can no longer be found. If the community still wants to use links instead of files, I can also use links to introduce static resources.

**Comment by liberhe** [comment]
> > Sorry, could you explain why not using links instead of files? Is it a private version?
> 
> Reply: Because the link only points to a resource address, the resource is easily changed. Especially if the reference link to the public repository changes and the corresponding maintenance personnel have left, the file may be permanently lost and can no longer be found. If the community still wants to use links instead of files, I can also use links to introduce static resources.

I see，We just do not want to make the project so large.   We will approve the pr. Thanks your contrubution again.

**Pull request merged**
