### PR TITLE
增加uniswap-v1工厂合约的逐行注解

### PR DESCRIPTION
**Pull request by Chonz-dot**
增加工厂合约的部分中文注解

### CODE REVIEW

**Review by maroonstar — APPROVED** [review]
Well done!

**Comment by maroonstar** [comment]
Please join our discord, and @admin to join develop group

**Comment by Chonz-dot** [comment]
> 请加入我们的discord，并@admin加入开发组
lol  !have already joined

**Comment by Chonz-dot** [comment]
> Please join our discord, and @admin to join develop group

有增加注释的需求吗?我还在学习solidity需要看这些代码,有看的懂的可以提交过来给你审核一下

**Comment by liberhe** [comment]
> > Please join our discord, and @admin to join develop group
> 
> 有增加注释的需求吗?我还在学习solidity需要看这些代码,有看的懂的可以提交过来给你审核一下

Of course it works. Look forward to more.

**Comment by maroonstar** [comment]
That's cool!

**Comment by liberhe** [comment]
> > Please join our discord, and @admin to join develop group
> 
> 有增加注释的需求吗?我还在学习solidity需要看这些代码,有看的懂的可以提交过来给你审核一下

It is recommend to add  test cases.

**Review by liberhe — APPROVED** [review]

**Pull request merged**
