### PR TITLE
Add flashswap Demo of uniswapV3

### PR DESCRIPTION
**Pull request by LowLowCoder-Mel**
- Contains complete uniswapv3 code and compiled
- Contains an easy-to-understand test script

### CODE REVIEW

**Comment by maroonstar** [comment]
So many files change....cloud you remove uniswapV3 contracts file , use npm libaray instead?(like @uniswap/v2-core, @uniswap/v3-core etc)

**Review by maroonstar — CHANGES_REQUESTED** [review]
So many files change....cloud you remove uniswapV3 contracts file , use npm libaray instead?(like @uniswap/v2-core, @uniswap/v3-core etc)

**Review by liushooter — APPROVED** [review]

**Comment by LowLowCoder-Mel** [comment]
> So many files change....cloud you remove uniswapV3 contracts file , use npm libaray instead?(like @uniswap/v2-core, @uniswap/v3-core etc)

Libraries are a great way to do this.  the reason why I did not use the library but use the source code is to better debug its call process, a deeper understanding of the call process.

**Comment by LowLowCoder-Mel** [comment]
> > So many files change....cloud you remove uniswapV3 contracts file , use npm libaray instead?(like @uniswap/v2-core, @uniswap/v3-core etc)
> 
> Libraries are a great way to do this. the reason why I did not use the library but use the source code is to better debug its call process, a deeper understanding of the call process.

Personally, I think hardhat's Console library is a great tool

**Comment by liberhe** [comment]
> * Contains complete uniswapv3 code and compiled
> * Contains an easy-to-understand test script

I have done a litter here,   https://github.com/rebase-network/Dapp-Learning/tree/main/defi/Uniswap-V3/frontGuid/sdk
you may add some change on it.  Please add a link in task20  is enough.

**Comment by liberhe** [comment]
> > > So many files change....cloud you remove uniswapV3 contracts file , use npm libaray instead?(like @uniswap/v2-core, @uniswap/v3-core etc)
> > 
> > 
> > Libraries are a great way to do this. the reason why I did not use the library but use the source code is to better debug its call process, a deeper understanding of the call process.
> 
> Personally, I think hardhat's Console library is a great tool
There is no need to add sol test file too .

**Comment by LowLowCoder-Mel** [comment]
> > > > So many files change....cloud you remove uniswapV3 contracts file , use npm libaray instead?(like @uniswap/v2-core, @uniswap/v3-core etc)
> > > 
> > > 
> > > Libraries are a great way to do this. the reason why I did not use the library but use the source code is to better debug its call process, a deeper understanding of the call process.
> > 
> > 
> > Personally, I think hardhat's Console library is a great tool
> > There is no need to add sol test file too .

Oh oh,  yeah.

**Pull request closed without merging**
