### PR TITLE
the compound V2 whitepaper understanding, the compound Protocol structure analysis, as well as the compound protocol deployment

### PR DESCRIPTION
**Pull request by bixia**
add Compound review from myside, including the compound V2 whitepaper understanding, the compound Protocol structure analysis, as well as the compound protocol deployment

### CODE REVIEW

**Review by jhfnetboy — DISMISSED** [review]
Wow, great~!

**Review by liberhe — APPROVED** [review]

**Review by liberhe — APPROVED** [review]

**Review by xrdavies — CHANGES_REQUESTED** [review]
Could you remove the pdf files and add the related links in markdown files?  Binary files are not friendly to GitHub and developers, and these pdf files are unnecessary in code.

**Review by jhfnetboy — COMMENTED** [review]
建议加marddown文档吧，这个好大

**Comment by bixia** [comment]
yes, i'll remove the PDF doc, instead add the link to the MD file

**Comment by bixia** [comment]
i have updated the PR as requested

**Review by liberhe — APPROVED** [review]

**Review by yingjingyang — APPROVED** [review]

**Review by maroonstar — APPROVED** [review]
Great!

**Review by liushooter — APPROVED** [review]

**Review by xrdavies — APPROVED** [review]
Looks good to me

**Pull request merged**
