### PR TITLE
update task

### PR DESCRIPTION
**Pull request by springrider**
增加参考示例

### CODE REVIEW

**Review by liberhe — COMMENTED** [review]
I see there is no solidity contract in the github project you mentioned

**Comment by springrider** [comment]
> I see there is no solidity contract in the github project you mentioned

maybe I misunderstood the purpose of this task, this wrapper is utilizing web3 to interactive with bsc.   could be useful  to learn how to use web3.py.

**Review by jhfnetboy — APPROVED** [review]
python...

**Comment by yanyanho** [comment]
> > I see there is no solidity contract in the github project you mentioned
> 
> maybe I misunderstood the purpose of this task, this wrapper is utilizing web3 to interactive with bsc. could be useful to learn how to use web3.py.

It is recommended to use eth or layer2 technology.

**Pull request closed without merging**
